---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=homebrew/cask

    - name: Tap bundle
      homebrew_tap: tap=homebrew/bundle

    - name: Update ansible
      homebrew:
        name: ansible
        state: latest

    - name: asdf git clone
      command: git clone https://github.com/asdf-vm/asdf.git ~/.asdf
      ignore_errors: yes
      register: result

    - name: "Create a default asdf configuration"
      template:
        src: templates/.asdfrc.j2
        dest: ~/.asdfrc
        force: yes

    - name: "Create a default asdf configuration"
      template:
        src: templates/.asdfrc.j2
        dest: ~/.asdfrc
        force: yes

    - name: "Install asdf plugins"
      shell: |
        source ~/.asdf/asdf.sh
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - nodejs

    - name: "Install default node"
      shell: |
        source ~/.asdf/asdf.sh
        bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
        asdf install nodejs 16.4.2
        asdf global nodejs 16.4.2

    - name: Install or Update mas
      homebrew:
        name: mas
        state: latest

    - name: Check dotfiles playbook
      stat:
        path: ~/dotfiles/osx/playbook.yml
      register: dotfiles_playbook

    - name: Install dotfiles
      include_tasks: ~/dotfiles/osx/playbook.yml
      when: dotfiles_playbook.stat.exists

    - name: Check brew bundle dump
      stat:
        path: ~/dotfiles/osx/Brewfile
      register: dotfiles_Brewfile

    - name: Install OSX Apps from Brewfile https://github.com/Homebrew/homebrew-bundle
      command: brew bundle --file ~/dotfiles/osx/Brewfile
      args:
        chdir: ~/dotfiles/osx/
      when: dotfiles_Brewfile.stat.exists
      register: result
      changed_when:
        - '"Installing" in result.stdout'
